name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Configuramos para disparar o CI/CD apenas para a branch master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Elastic Beanstalk
        env:
          APPLICATION_NAME: "zlo-login-microservice" # Nome da aplicação - Elastic Beanstalk
          ENVIRONMENT_NAME: "zlo-login-microservice-env-2" # Nome do ambiente - Elastic Beanstalk
          S3_BUCKET: "elasticbeanstalk-us-east-1-476114126279" # Nome do bucket S3 usado pelo Elastic Beanstalk
        run: |
          zip -r application.zip .
          aws s3 cp application.zip s3://$S3_BUCKET/$APPLICATION_NAME/application.zip
          aws elasticbeanstalk create-application-version --application-name $APPLICATION_NAME --version-label $GITHUB_SHA --source-bundle S3Bucket=$S3_BUCKET,S3Key=$APPLICATION_NAME/application.zip
          aws elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $GITHUB_SHA
